site_name: 伟子时代
site_url: https://weizi-era.github.io/
site_description: 关于学习Android的知识点以及工作过程中遇到的问题记录
site_author: weizi-era
theme:
    name: material
    highlightjs: true
    favicon: assets/Blog.ico
    logo: assets/icon.jpg
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: white
        accent: blue
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: blue
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    font:
      text: Roboto
      code: Roboto Mono

    language: zh

    feature:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
    #- navigation.sections
      - navigation.top
      - header.autohide
      - navigation.expand


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
    
    search:
        language: 'zh,en,ja'
        tokenizer: '[\ s \-\ .. +'
    palette:
        primary: 'Blue Grey'
        accent: 'Pink'
    

nav:
    - 介绍: index.md
    - 技术博文:  
       - Android:
           - 流媒体服务器搭建: android/media_server_build.md
           - Android系统启动流程: android/android_startup.md
           - app启动流程: android/app_startup.md
    - 关于: about.md

copyright: Copyright &copy; 2016 - 2021 weizi-era
